// Curated app metadata and icon candidates, separate from matching state.
.pragma library

var KNOWN_APP_DEFAULTS = {
    "syncterm": { id: "syncterm", icon: "syncterm", rawIcon: "syncterm", name: "SyncTERM" },
    "claude": { id: "claude-desktop", icon: "claude-desktop", rawIcon: "claude-desktop", name: "Claude" },
    "claude-desktop": { id: "claude-desktop", icon: "claude-desktop", rawIcon: "claude-desktop", name: "Claude" },
    "claude desktop": { id: "claude-desktop", icon: "claude-desktop", rawIcon: "claude-desktop", name: "Claude" },
    "code": { id: "code", icon: "vscode", rawIcon: "vscode", name: "Visual Studio Code" },
    "vscode": { id: "code", icon: "vscode", rawIcon: "vscode", name: "Visual Studio Code" },
    "org.kde.kwrite": { id: "org.kde.kwrite", icon: "kwrite", rawIcon: "kwrite", name: "KWrite" },
    "kwrite": { id: "org.kde.kwrite", icon: "kwrite", rawIcon: "kwrite", name: "KWrite" },
    "org.kde.krita": { id: "org.kde.krita", icon: "krita", rawIcon: "krita", name: "Krita" },
    "krita": { id: "org.kde.krita", icon: "krita", rawIcon: "krita", name: "Krita" },
    "org.kde.dolphin": { id: "org.kde.dolphin", icon: "org.kde.dolphin", rawIcon: "org.kde.dolphin", name: "Dolphin" },
    "dolphin": { id: "org.kde.dolphin", icon: "org.kde.dolphin", rawIcon: "org.kde.dolphin", name: "Dolphin" },
    "com.mitchellh.ghostty": { id: "com.mitchellh.ghostty", icon: "com.mitchellh.ghostty", rawIcon: "com.mitchellh.ghostty", name: "Ghostty" },
    "ghostty": { id: "com.mitchellh.ghostty", icon: "com.mitchellh.ghostty", rawIcon: "com.mitchellh.ghostty", name: "Ghostty" },
    "google-chrome": { id: "google-chrome", icon: "google-chrome", rawIcon: "google-chrome", name: "Google Chrome" },
    "steam": { id: "steam", icon: "steam", rawIcon: "steam", name: "Steam" },
    "antigravity": { id: "antigravity", icon: "antigravity", rawIcon: "antigravity", name: "Antigravity" },
    "libreoffice-writer": { id: "libreoffice-writer", icon: "libreoffice-writer", rawIcon: "libreoffice-writer", name: "LibreOffice Writer" },
    "libreoffice-impress": { id: "libreoffice-impress", icon: "libreoffice-impress", rawIcon: "libreoffice-impress", name: "LibreOffice Impress" },
    "libreoffice-calc": { id: "libreoffice-calc", icon: "libreoffice-calc", rawIcon: "libreoffice-calc", name: "LibreOffice Calc" },
    "discord": { id: "discord", icon: "omarchy-discord", rawIcon: "omarchy-discord", name: "Discord" },
    "google-photos": { id: "Google Photos", icon: "google-photos", rawIcon: "google-photos", name: "Google Photos" },
    "photos.google.com": { id: "Google Photos", icon: "google-photos", rawIcon: "google-photos", name: "Google Photos" },
    "chrome-photos.google.com__-default": { id: "Google Photos", icon: "google-photos", rawIcon: "google-photos", name: "Google Photos" },
    "google-contacts": { id: "Google Contacts", icon: "google-contacts", rawIcon: "google-contacts", name: "Google Contacts" },
    "contacts.google.com": { id: "Google Contacts", icon: "google-contacts", rawIcon: "google-contacts", name: "Google Contacts" },
    "chrome-contacts.google.com__-default": { id: "Google Contacts", icon: "google-contacts", rawIcon: "google-contacts", name: "Google Contacts" },
    "google-messages": { id: "Google Messages", icon: "google-messages", rawIcon: "google-messages", name: "Google Messages" },
    "messages.google.com": { id: "Google Messages", icon: "google-messages", rawIcon: "google-messages", name: "Google Messages" },
    "chrome-messages.google.com__web_conversations-default": { id: "Google Messages", icon: "google-messages", rawIcon: "google-messages", name: "Google Messages" },
    "google-maps": { id: "Google Maps", icon: "google-maps", rawIcon: "google-maps", name: "Google Maps" },
    "maps.google.com": { id: "Google Maps", icon: "google-maps", rawIcon: "google-maps", name: "Google Maps" },
    "chrome-maps.google.com__-default": { id: "Google Maps", icon: "google-maps", rawIcon: "google-maps", name: "Google Maps" },
    "gmail": { id: "Gmail", icon: "gmail", rawIcon: "gmail", name: "Gmail" },
    "mail.google.com": { id: "Gmail", icon: "gmail", rawIcon: "gmail", name: "Gmail" },
    "google-calendar": { id: "Google Calendar", icon: "google-calendar", rawIcon: "google-calendar", name: "Google Calendar" },
    "calendar.google.com": { id: "Google Calendar", icon: "google-calendar", rawIcon: "google-calendar", name: "Google Calendar" },
    "google-drive": { id: "Google Drive", icon: "google-drive", rawIcon: "google-drive", name: "Google Drive" },
    "drive.google.com": { id: "Google Drive", icon: "google-drive", rawIcon: "google-drive", name: "Google Drive" },
    "google-keep": { id: "Google Keep", icon: "google-keep", rawIcon: "google-keep", name: "Google Keep" },
    "keep.google.com": { id: "Google Keep", icon: "google-keep", rawIcon: "google-keep", name: "Google Keep" },
    "youtube": { id: "YouTube", icon: "youtube", rawIcon: "youtube", name: "YouTube" },
    "youtube.com": { id: "YouTube", icon: "youtube", rawIcon: "youtube", name: "YouTube" },
    "youtube-music": { id: "YouTube Music", icon: "youtube-music", rawIcon: "youtube-music", name: "YouTube Music" },
    "music.youtube.com": { id: "YouTube Music", icon: "youtube-music", rawIcon: "youtube-music", name: "YouTube Music" },
    "yandex-mail": { id: "Яндекс Почта", icon: "yandex-mail", rawIcon: "yandex-mail", name: "Яндекс Почта" },
    "mail.yandex.ru": { id: "Яндекс Почта", icon: "yandex-mail", rawIcon: "yandex-mail", name: "Яндекс Почта" },
    "yandex-music": { id: "Яндекс Музыка", icon: "yandex-music", rawIcon: "yandex-music", name: "Яндекс Музыка" },
    "music.yandex.ru": { id: "Яндекс Музыка", icon: "yandex-music", rawIcon: "yandex-music", name: "Яндекс Музыка" },
    "photoshop": { id: "Photoshop 2017", icon: "Photoshop2017", rawIcon: "Photoshop2017", name: "Photoshop 2017" },
    "photoshop 2017": { id: "Photoshop 2017", icon: "Photoshop2017", rawIcon: "Photoshop2017", name: "Photoshop 2017" },
    "yazi": { id: "yazi", icon: "yazi", rawIcon: "yazi", name: "Yazi" },
    "nvim": { id: "nvim", icon: "nvim", rawIcon: "nvim", name: "Neovim" },
    "neovim": { id: "nvim", icon: "nvim", rawIcon: "nvim", name: "Neovim" },
    "vim": { id: "vim", icon: "vim", rawIcon: "vim", name: "Vim" },
    "nano": { id: "nano", icon: "nano", rawIcon: "nano", name: "GNU nano" },
    "micro": { id: "micro", icon: "micro", rawIcon: "micro", name: "Micro" },
    "helix": { id: "helix", icon: "helix", rawIcon: "helix", name: "Helix" },
    "hx": { id: "helix", icon: "helix", rawIcon: "helix", name: "Helix" },
    "btop": { id: "btop", icon: "btop", rawIcon: "btop", name: "btop" },
    "htop": { id: "htop", icon: "htop", rawIcon: "htop", name: "htop" },
    "ranger": { id: "ranger", icon: "ranger", rawIcon: "ranger", name: "Ranger" },
    "mc": { id: "mc", icon: "mc", rawIcon: "mc", name: "Midnight Commander" },
    "lazygit": { id: "lazygit", icon: "lazygit", rawIcon: "lazygit", name: "LazyGit" },
    "fastfetch": { id: "fastfetch", icon: "fastfetch", rawIcon: "fastfetch", name: "Fastfetch" },
    "brave": { id: "brave-browser", icon: "brave-desktop", rawIcon: "brave-desktop", name: "Brave" },
    "brave-browser": { id: "brave-browser", icon: "brave-desktop", rawIcon: "brave-desktop", name: "Brave" },
    "transmission": { id: "transmission-gtk", icon: "transmission-gtk", rawIcon: "transmission-gtk", name: "Transmission" },
    "transmission-gtk": { id: "transmission-gtk", icon: "transmission-gtk", rawIcon: "transmission-gtk", name: "Transmission" },
    "transmission-qt": { id: "transmission-qt", icon: "transmission-qt", rawIcon: "transmission-qt", name: "Transmission" },
    "com.transmissionbt.transmission": { id: "transmission-gtk", icon: "transmission-gtk", rawIcon: "transmission-gtk", name: "Transmission" },
    "yandex-browser": { id: "yandex-browser", icon: "yandex-browser", rawIcon: "yandex-browser", name: "Yandex Browser" },
    "yandex-browser-stable": { id: "yandex-browser", icon: "yandex-browser", rawIcon: "yandex-browser", name: "Yandex Browser" },
    "ru.yandex.desktop.browser": { id: "yandex-browser", icon: "yandex-browser", rawIcon: "yandex-browser", name: "Yandex Browser" },
    "x": { id: "X", icon: "x", rawIcon: "x", name: "X" },
    "x.com": { id: "X", icon: "x", rawIcon: "x", name: "X" },
    "chrome-x.com__-default": { id: "X", icon: "x", rawIcon: "x", name: "X" },
    "twitter": { id: "X", icon: "twitter-x", rawIcon: "twitter-x", name: "X" },
    "twitter.com": { id: "X", icon: "twitter-x", rawIcon: "twitter-x", name: "X" },
    "basecamp": { id: "Basecamp", icon: "basecamp", rawIcon: "basecamp", name: "Basecamp" },
    "launchpad.37signals.com": { id: "Basecamp", icon: "basecamp", rawIcon: "basecamp", name: "Basecamp" },
    "chrome-launchpad.37signals.com__-default": { id: "Basecamp", icon: "basecamp", rawIcon: "basecamp", name: "Basecamp" },
    "hey": { id: "HEY", icon: "hey", rawIcon: "hey", name: "HEY" },
    "whatsapp": { id: "WhatsApp", icon: "whatsapp", rawIcon: "whatsapp", name: "WhatsApp" },
    "web.whatsapp.com": { id: "WhatsApp", icon: "whatsapp", rawIcon: "whatsapp", name: "WhatsApp" },
    "chrome-web.whatsapp.com__-default": { id: "WhatsApp", icon: "whatsapp", rawIcon: "whatsapp", name: "WhatsApp" },
    "zoom": { id: "Zoom", icon: "zoom", rawIcon: "zoom", name: "Zoom" },
    "cursor": { id: "Cursor", icon: "cursor", rawIcon: "cursor", name: "Cursor" },
    "chrome-appgkjomdnhhdolojlpkjafpklojikld-default": { id: "Cursor", icon: "cursor", rawIcon: "cursor", name: "Cursor" },
    "xdg-desktop-portal-gtk": { id: "xdg-desktop-portal-gtk", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "org.freedesktop.impl.portal.desktop.gtk": { id: "org.freedesktop.impl.portal.desktop.gtk", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "xdg-desktop-portal-gnome": { id: "xdg-desktop-portal-gnome", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "org.freedesktop.impl.portal.desktop.gnome": { id: "org.freedesktop.impl.portal.desktop.gnome", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "xdg-desktop-portal-kde": { id: "xdg-desktop-portal-kde", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "org.freedesktop.impl.portal.desktop.kde": { id: "org.freedesktop.impl.portal.desktop.kde", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "xdg-desktop-portal-lxqt": { id: "xdg-desktop-portal-lxqt", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "org.freedesktop.impl.portal.desktop.lxqt": { id: "org.freedesktop.impl.portal.desktop.lxqt", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "xdg-desktop-portal-hyprland": { id: "xdg-desktop-portal-hyprland", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "org.freedesktop.impl.portal.desktop.hyprland": { id: "org.freedesktop.impl.portal.desktop.hyprland", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "xdg-desktop-portal-wlr": { id: "xdg-desktop-portal-wlr", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "org.freedesktop.impl.portal.desktop.wlr": { id: "org.freedesktop.impl.portal.desktop.wlr", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "xdg-desktop-portal": { id: "xdg-desktop-portal", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "org.freedesktop.portal": { id: "org.freedesktop.portal", icon: "document-open", rawIcon: "document-open", name: "File Chooser" },
    "zenity": { id: "zenity", icon: "dialog-information", rawIcon: "dialog-information", name: "Dialog" },
    "kdialog": { id: "kdialog", icon: "dialog-information", rawIcon: "dialog-information", name: "Dialog" },
    "hyprpolkitagent": { id: "hyprpolkitagent", icon: "dialog-password", rawIcon: "dialog-password", name: "Authentication" },
    "polkit-gnome-authentication-agent-1": { id: "polkit-gnome-authentication-agent-1", icon: "dialog-password", rawIcon: "dialog-password", name: "Authentication" },
    "org.kde.polkit-kde-authentication-agent-1": { id: "org.kde.polkit-kde-authentication-agent-1", icon: "dialog-password", rawIcon: "dialog-password", name: "Authentication" },
    "pavucontrol": { id: "pavucontrol", icon: "multimedia-volume-control", rawIcon: "multimedia-volume-control", name: "Volume Control" },
    "org.pulseaudio.pavucontrol": { id: "pavucontrol", icon: "multimedia-volume-control", rawIcon: "multimedia-volume-control", name: "Volume Control" },
    "pwvucontrol": { id: "pwvucontrol", icon: "multimedia-volume-control", rawIcon: "multimedia-volume-control", name: "PipeWire Volume Control" },
    "com.saivert.pwvucontrol": { id: "pwvucontrol", icon: "multimedia-volume-control", rawIcon: "multimedia-volume-control", name: "PipeWire Volume Control" },
    "satty": { id: "satty", icon: "accessories-screenshot", rawIcon: "accessories-screenshot", name: "Satty" },
    "com.gabm.satty": { id: "satty", icon: "accessories-screenshot", rawIcon: "accessories-screenshot", name: "Satty" },
    "flameshot": { id: "flameshot", icon: "flameshot", rawIcon: "flameshot", name: "Flameshot" },
    "org.flameshot.Flameshot": { id: "flameshot", icon: "flameshot", rawIcon: "flameshot", name: "Flameshot" },
    "file-roller": { id: "file-roller", icon: "utilities-file-archiver", rawIcon: "utilities-file-archiver", name: "Archive Manager" },
    "org.gnome.FileRoller": { id: "file-roller", icon: "utilities-file-archiver", rawIcon: "utilities-file-archiver", name: "Archive Manager" },
    "ark": { id: "ark", icon: "utilities-file-archiver", rawIcon: "utilities-file-archiver", name: "Ark" },
    "org.kde.ark": { id: "ark", icon: "utilities-file-archiver", rawIcon: "utilities-file-archiver", name: "Ark" },
    "imv": { id: "imv", icon: "image-viewer", rawIcon: "image-viewer", name: "Image Viewer" },
    "swayimg": { id: "swayimg", icon: "image-viewer", rawIcon: "image-viewer", name: "Image Viewer" },
    "feh": { id: "feh", icon: "image-viewer", rawIcon: "image-viewer", name: "feh" },
    "zathura": { id: "zathura", icon: "document-viewer", rawIcon: "document-viewer", name: "Zathura" },
    "org.pwmt.zathura": { id: "zathura", icon: "document-viewer", rawIcon: "document-viewer", name: "Zathura" },
    "galculator": { id: "galculator", icon: "accessories-calculator", rawIcon: "accessories-calculator", name: "Calculator" },
    "gnome-calculator": { id: "gnome-calculator", icon: "accessories-calculator", rawIcon: "accessories-calculator", name: "Calculator" },
    "org.gnome.Calculator": { id: "gnome-calculator", icon: "accessories-calculator", rawIcon: "accessories-calculator", name: "Calculator" },
    "cliamp": { id: "cliamp", icon: "cliamp", rawIcon: "cliamp", name: "cliamp" },
    "org.omarchy.cliamp": { id: "cliamp", icon: "cliamp", rawIcon: "cliamp", name: "cliamp" }
};

var FALLBACK_ICON_CANDIDATES = {
    "syncterm": ["syncterm", "utilities-terminal", "terminal"],
    "claude": ["claude-desktop", "claude", "anthropic", "chat-claude"],
    "claude-desktop": ["claude-desktop", "claude", "anthropic", "chat-claude"],
    "claude desktop": ["claude-desktop", "claude", "anthropic", "chat-claude"],
    "brave": ["brave-desktop", "brave-browser", "brave"],
    "brave-browser": ["brave-desktop", "brave-browser", "brave"],
    "transmission": ["transmission-gtk", "transmission", "com.transmissionbt.Transmission", "transmission-qt"],
    "transmission-gtk": ["transmission-gtk", "transmission", "com.transmissionbt.Transmission", "transmission-qt"],
    "transmission-qt": ["transmission-qt", "transmission", "com.transmissionbt.Transmission", "transmission-gtk"],
    "com.transmissionbt.transmission": ["transmission-gtk", "transmission", "com.transmissionbt.Transmission", "transmission-qt"],
    "yandex-browser": ["yandex-browser", "yandex-browser-stable", "ru.yandex.desktop.browser", "yandex"],
    "yandex-browser-stable": ["yandex-browser", "yandex-browser-stable", "ru.yandex.desktop.browser", "yandex"],
    "ru.yandex.desktop.browser": ["yandex-browser", "yandex-browser-stable", "ru.yandex.desktop.browser", "yandex"],
    "x": ["x", "twitter-x", "twitter", "solstice-twitter-twitter", "unity-webapps-twitter"],
    "x.com": ["x", "twitter-x", "twitter", "solstice-twitter-twitter", "unity-webapps-twitter"],
    "chrome-x.com__-default": ["x", "twitter-x", "twitter"],
    "twitter": ["twitter-x", "twitter", "x", "solstice-twitter-twitter", "unity-webapps-twitter"],
    "twitter.com": ["twitter-x", "twitter", "x"],
    "basecamp": ["basecamp"],
    "launchpad.37signals.com": ["basecamp"],
    "chrome-launchpad.37signals.com__-default": ["basecamp"],
    "hey": ["hey", "mail-client", "internet-mail"],
    "whatsapp": ["whatsapp", "whatsapp-for-linux", "com.whatsapp.WhatsApp"],
    "web.whatsapp.com": ["whatsapp", "whatsapp-for-linux", "com.whatsapp.WhatsApp"],
    "chrome-web.whatsapp.com__-default": ["whatsapp", "whatsapp-for-linux", "com.whatsapp.WhatsApp"],
    "zoom": ["zoom", "Zoom", "us.zoom.Zoom"],
    "cursor": ["cursor", "cursor-editor", "code", "com.visualstudio.code"],
    "chrome-appgkjomdnhhdolojlpkjafpklojikld-default": ["cursor", "cursor-editor", "code", "com.visualstudio.code"],
    "ghostty": ["com.mitchellh.ghostty", "ghostty"],
    "com.mitchellh.ghostty": ["com.mitchellh.ghostty", "ghostty"],
    "yazi": ["yazi", "system-file-manager"],
    "nvim": ["nvim", "neovim", "text-editor"],
    "neovim": ["nvim", "neovim", "text-editor"],
    "vim": ["vim", "text-editor"],
    "nano": ["nano", "text-editor"],
    "micro": ["micro", "text-editor"],
    "helix": ["helix", "text-editor"],
    "btop": ["btop", "utilities-system-monitor"],
    "htop": ["htop", "utilities-system-monitor"],
    "ranger": ["ranger", "system-file-manager"],
    "mc": ["mc", "MidnightCommander", "system-file-manager"],
    "lazygit": ["lazygit", "git"],
    "lazydocker": ["lazydocker", "docker"],
    "ncmpcpp": ["ncmpcpp", "audio-player", "multimedia-audio-player"],
    "cmus": ["cmus", "audio-player", "multimedia-audio-player"],
    "code": ["com.visualstudio.code", "visual-studio-code", "visualstudiocode", "code-oss", "vscode", "code"],
    "vscode": ["com.visualstudio.code", "visual-studio-code", "visualstudiocode", "code-oss", "vscode", "code"],
    "com.visualstudio.code": ["com.visualstudio.code", "visual-studio-code", "visualstudiocode", "code-oss", "vscode", "code"],
    "dolphin": ["org.kde.dolphin", "dolphin", "system-file-manager"],
    "org.kde.dolphin": ["org.kde.dolphin", "dolphin", "system-file-manager"],
    "nautilus": ["org.gnome.Nautilus", "org.gnome.nautilus", "nautilus", "system-file-manager", "file-manager"],
    "org.gnome.nautilus": ["org.gnome.Nautilus", "org.gnome.nautilus", "nautilus", "system-file-manager", "file-manager"],
    "org.gnome.Nautilus": ["org.gnome.Nautilus", "org.gnome.nautilus", "nautilus", "system-file-manager", "file-manager"],
    "files": ["org.gnome.Nautilus", "org.gnome.nautilus", "nautilus", "system-file-manager", "file-manager"],
    "kwrite": ["org.kde.kwrite", "kwrite"],
    "org.kde.kwrite": ["org.kde.kwrite", "kwrite"],
    "krita": ["org.kde.krita", "krita"],
    "org.kde.krita": ["org.kde.krita", "krita"],
    "google-chrome": ["google-chrome", "chrome", "google-chrome-stable"],
    "steam": ["steam", "steam-launcher"],
    "antigravity": ["antigravity"],
    "libreoffice-writer": ["libreoffice-writer", "libreoffice-oasis-writer"],
    "libreoffice-calc": ["libreoffice-calc", "libreoffice-oasis-calc"],
    "libreoffice-impress": ["libreoffice-impress", "libreoffice-oasis-impress"],
    "discord": ["omarchy-discord", "discord", "com.discordapp.Discord"],
    "telegram": ["org.telegram.desktop", "telegram", "telegramdesktop", "org.telegram"],
    "org.telegram": ["org.telegram.desktop", "telegram", "telegramdesktop", "org.telegram"],
    "telegramdesktop": ["org.telegram.desktop", "telegram", "telegramdesktop", "org.telegram"],
    "obsidian": ["obsidian", "md.obsidian.Obsidian"],
    "spotify": ["spotify", "spotify-client"],
    "google-photos": ["google-photos", "photos", "googlephotos"],
    "photos": ["google-photos", "photos"],
    "photos.google.com": ["google-photos", "photos"],
    "chrome-photos.google.com__-default": ["google-photos", "photos"],
    "google-contacts": ["google-contacts", "contacts", "googlecontacts"],
    "contacts": ["google-contacts", "contacts"],
    "contacts.google.com": ["google-contacts", "contacts"],
    "chrome-contacts.google.com__-default": ["google-contacts", "contacts"],
    "google-messages": ["google-messages", "messages", "googlemessages"],
    "messages": ["google-messages", "messages"],
    "messages.google.com": ["google-messages", "messages"],
    "chrome-messages.google.com__web_conversations-default": ["google-messages", "messages"],
    "google-maps": ["google-maps", "maps", "googlemaps"],
    "maps.google.com": ["google-maps", "maps"],
    "chrome-maps.google.com__-default": ["google-maps", "maps"],
    "gmail": ["gmail", "google-gmail", "mail-google"],
    "mail.google.com": ["gmail", "google-gmail"],
    "google-calendar": ["google-calendar", "calendar-google"],
    "calendar.google.com": ["google-calendar", "calendar-google"],
    "google-drive": ["google-drive", "drive-google"],
    "drive.google.com": ["google-drive", "drive-google"],
    "google-keep": ["google-keep", "keep-google"],
    "keep.google.com": ["google-keep", "keep-google"],
    "youtube": ["youtube", "youtube-browser"],
    "youtube.com": ["youtube", "youtube-browser"],
    "youtube-music": ["youtube-music", "music-youtube"],
    "music.youtube.com": ["youtube-music", "music-youtube"],
    "yandex-mail": ["yandex-mail", "mail-yandex", "yandex-browser-mail"],
    "mail.yandex.ru": ["yandex-mail", "mail-yandex"],
    "yandex-music": ["yandex-music", "music-yandex"],
    "music.yandex.ru": ["yandex-music", "music-yandex"],
    "photoshop": ["Photoshop2017", "photoshop", "adobe-photoshop"],
    "photoshop 2017": ["Photoshop2017", "photoshop", "adobe-photoshop"],
    "xdg-desktop-portal-gtk": ["document-open", "document-save-as", "document-save", "system-file-manager", "org.gnome.Nautilus", "file-manager", "folder"],
    "org.freedesktop.impl.portal.desktop.gtk": ["document-open", "document-save-as", "document-save", "system-file-manager", "org.gnome.Nautilus", "file-manager", "folder"],
    "xdg-desktop-portal-gnome": ["document-open", "document-save-as", "document-save", "system-file-manager", "org.gnome.Nautilus", "file-manager", "folder"],
    "org.freedesktop.impl.portal.desktop.gnome": ["document-open", "document-save-as", "document-save", "system-file-manager", "org.gnome.Nautilus", "file-manager", "folder"],
    "xdg-desktop-portal-kde": ["document-open", "document-save-as", "document-save", "system-file-manager", "org.kde.dolphin", "dolphin", "file-manager", "folder"],
    "org.freedesktop.impl.portal.desktop.kde": ["document-open", "document-save-as", "document-save", "system-file-manager", "org.kde.dolphin", "dolphin", "file-manager", "folder"],
    "xdg-desktop-portal-lxqt": ["document-open", "document-save-as", "document-save", "system-file-manager", "file-manager", "folder"],
    "org.freedesktop.impl.portal.desktop.lxqt": ["document-open", "document-save-as", "document-save", "system-file-manager", "file-manager", "folder"],
    "xdg-desktop-portal-hyprland": ["document-open", "document-save-as", "document-save", "system-file-manager", "file-manager", "folder"],
    "org.freedesktop.impl.portal.desktop.hyprland": ["document-open", "document-save-as", "document-save", "system-file-manager", "file-manager", "folder"],
    "xdg-desktop-portal-wlr": ["document-open", "document-save-as", "document-save", "system-file-manager", "file-manager", "folder"],
    "org.freedesktop.impl.portal.desktop.wlr": ["document-open", "document-save-as", "document-save", "system-file-manager", "file-manager", "folder"],
    "xdg-desktop-portal": ["document-open", "document-save-as", "document-save", "system-file-manager", "file-manager", "folder"],
    "org.freedesktop.portal": ["document-open", "document-save-as", "document-save", "system-file-manager", "file-manager", "folder"],
    "zenity": ["dialog-information", "dialog-question", "dialog-warning", "utilities-terminal"],
    "kdialog": ["dialog-information", "dialog-question", "dialog-warning", "utilities-terminal"],
    "hyprpolkitagent": ["dialog-password", "security-high", "system-lock-screen", "preferences-system"],
    "polkit-gnome-authentication-agent-1": ["dialog-password", "security-high", "system-lock-screen", "preferences-system"],
    "org.kde.polkit-kde-authentication-agent-1": ["dialog-password", "security-high", "system-lock-screen", "preferences-system"],
    "pavucontrol": ["multimedia-volume-control", "audio-card", "pavucontrol", "audio-volume-high"],
    "org.pulseaudio.pavucontrol": ["multimedia-volume-control", "audio-card", "pavucontrol", "audio-volume-high"],
    "pwvucontrol": ["multimedia-volume-control", "audio-card", "pwvucontrol", "audio-volume-high"],
    "com.saivert.pwvucontrol": ["multimedia-volume-control", "audio-card", "pwvucontrol", "audio-volume-high"],
    "satty": ["accessories-screenshot", "applets-screenshooter", "accessories-image-viewer"],
    "com.gabm.satty": ["accessories-screenshot", "applets-screenshooter", "accessories-image-viewer"],
    "flameshot": ["flameshot", "accessories-screenshot", "applets-screenshooter"],
    "org.flameshot.Flameshot": ["flameshot", "accessories-screenshot", "applets-screenshooter"],
    "file-roller": ["utilities-file-archiver", "archive-manager", "file-roller", "org.gnome.FileRoller"],
    "org.gnome.FileRoller": ["utilities-file-archiver", "archive-manager", "file-roller", "org.gnome.FileRoller"],
    "ark": ["utilities-file-archiver", "archive-manager", "ark", "org.kde.ark"],
    "org.kde.ark": ["utilities-file-archiver", "archive-manager", "ark", "org.kde.ark"],
    "imv": ["image-viewer", "accessories-image-viewer", "multimedia-photo-viewer"],
    "swayimg": ["image-viewer", "accessories-image-viewer", "multimedia-photo-viewer"],
    "feh": ["image-viewer", "accessories-image-viewer", "feh"],
    "zathura": ["document-viewer", "application-pdf", "org.pwmt.zathura"],
    "org.pwmt.zathura": ["document-viewer", "application-pdf", "org.pwmt.zathura"],
    "galculator": ["accessories-calculator", "calc", "calculator"],
    "gnome-calculator": ["accessories-calculator", "calc", "calculator", "org.gnome.Calculator"],
    "org.gnome.Calculator": ["accessories-calculator", "calc", "calculator", "org.gnome.Calculator"],
    "cliamp": ["cliamp", "audio-player", "multimedia-audio-player", "music"],
    "org.omarchy.cliamp": ["cliamp", "audio-player", "multimedia-audio-player", "music"],
    "soffice": ["libreoffice-startcenter", "libreoffice-main", "document-viewer", "accessories-text-editor"],
    "spotify": ["spotify-client", "spotify", "audio-player", "multimedia-audio-player"],
    "com.spotify.client": ["spotify-client", "spotify", "audio-player"],
    "obsidian": ["md.obsidian.Obsidian", "obsidian", "accessories-text-editor"],
    "md.obsidian.obsidian": ["obsidian", "md.obsidian.Obsidian", "accessories-text-editor"],
    "lite_xl": ["lite-xl", "lite_xl", "text-editor", "accessories-text-editor"],
    "lite-xl": ["lite-xl", "lite_xl", "text-editor", "accessories-text-editor"],
    "com.lite_xl.litexl": ["lite-xl", "lite_xl", "text-editor", "accessories-text-editor"],
    "xdg-desktop-portal-gtk": ["document-open", "file-manager", "preferences-desktop"]
};

